= Extending Mule to Documentation

== What this Means?

Documentation process can involve integrated validation, design and debugging of Mule applications within enabled writing environments.

== Atom Packages Used/Tested

* `script`, yes, it's called "script".
** *Command + I* to run script, and you see the cmd console in your Atom window, below your text editor.

Saving a simple script and running it from Atom will get your Mule server up and running, with the result seen within Atom itself. With a few small modifications, we hope we can pass an application file to the server to run and see the result in Atom.

----
cd /Applications/mmc-distribution-mule-console-bundle-3.7.0
7777 | ./startup.sh
----

[NOTE]
This `script` package is initially used only to run the test script, not much more. Also, with the "Run By Line" feature fully enabled we can inject subsequent commands into command line, not just run the script file.

We hope to pass application xml as command line arguments for command line debugging.
https://docs.mulesoft.com/mule-user-guide/v/3.7/debugging-outside-studio

Calling Mule:

[source,bash,linenums]
----
ML-AARUJ-OSX-SF:mmc-distribution-mule-console-bundle-3.7.0 alex.aruj$ ls
mmc-3.7.0		shutdown.sh		status.sh
mule-enterprise-3.7.0	startup.bat
shutdown.bat		startup.sh
ML-AARUJ-OSX-SF:mmc-distribution-mule-console-bundle-3.7.0 alex.aruj$ cd mule-enterprise-3.7.0/
ML-AARUJ-OSX-SF:mule-enterprise-3.7.0 alex.aruj$ ls
LICENSE.txt	apps		conf		examples	plugins
MIGRATION.txt	autorun.groovy	docs		lib		src
README.txt	bin		domains		logs		tools
ML-AARUJ-OSX-SF:mule-enterprise-3.7.0 alex.aruj$ cd bin
ML-AARUJ-OSX-SF:bin alex.aruj$ ls
additional.groovy	launcher.bat		populate_m2_repo
amc_setup		launcher.conf		populate_m2_repo.cmd
amc_setup.bat		mule			populate_m2_repo.groovy
launcher		mule.bat
----

== Debugging Command
[source,bash]
----
$MULE_HOME/bin/mule -debug
----

== Taking Advantage of Hot Redeployment

https://docs.mulesoft.com/mule-user-guide/v/3.7/application-deployment#application-hot-deployment

== Using REST to Debug in Remote Console

https://docs.mulesoft.com/mule-management-console/v/3.7/repository-of-applications
